repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        args: [
            --application-directories, '.:src',
            --py38-plus,
            --add-import, 'from __future__ import annotations',
        ]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        args: [--line-length=79]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        exclude: ^(cli|lib/aws/actions.py|lib/aws/definitions.py|lib/aws/attacks.py|lib/aws/ingestor.py|lib/aws/resources.py|lib/aws/policy.py) # to change
# -   repo: https://github.com/pre-commit/mirrors-mypy # to change
#     rev: v1.8.0
#     hooks:
#     -   id: mypy
#         exclude: ^lib/aws
